### ISSUE TITLE
the --nodeVersion flag should accept -staging

### ISSUE THREAD

**Issue by lance** [bucharest-gold/nodeshift#167]
At the moment, the `--nodeVersion` flag has a limited set of acceptable options. When trying to test new versions of the builder image, it would be nice to be able to specify something like `--nodeVersion=v8.x-staging` so that I don't have to publish new images to test them out.

**Comment by lholmquist** [comment]
this also comes into play when a new version node image is released, like 10.x,  we will have to manually update nodeshift to allow someone to specify that version.  

it is sort of nice to have this list, since it helps the developer not pick something that doesn't exist, but then there are situations like you are describing.

**Comment by lholmquist** [comment]
@lance what do think about also getting rid of version 5 and 4 from the choices list.  probably do it in another PR

**Comment by lance** [comment]
Definitely - 4 and 5 are both EOL.
