### ISSUE TITLE
Creating an express-based service with nodeshift assumes port 8080 but express defaults to 3000

### ISSUE THREAD

**Issue by stephanosbacon** [bucharest-gold/nodeshift#230]
This is straightfoward to work around with --deploy.port, and nodeshift --help does say that it defaults to port 8080, but the happy path of express-generator.... nodeshift deploy  doesn't "just work".

**Comment by lholmquist** [comment]
I had created this issue, #214, which would add an environment variable for PORT=8080 to your deployment config by default which would make a base express-generator deploy just work.  But it just didn't feel right, since we already had --deploy.port.

The only reason 8080 was chosen as a default was becuase thats what the maven plugin was doing, and 8080 is, to me, a very Jboss-y port

I don't think making 3000 the default is the right thing here, since, if something other than express was used, like hapi for instance, the port could be different

i might have missed something,  but what was the question here?

**Comment by stephanosbacon** [comment]
This is one of those "there's no real right answer" issues.  The only thing I can think of is to show an express app as the default getting started example and just show --deploy.port.  That way, what I would expect would be a pretty common "hey let me try this out pattern" would just work.

**Comment by lholmquist** [comment]
"Actually, I think your PORT=8080 idea is fine too..."

I think my ultimate reason to not add any environment variables by default, was i didn't want to much magic happening.  I wanted "just enough magic"  :)

**Comment by lholmquist** [comment]
I agree though, we should have an example application showing this pattern.

I wrote my blog post on zero to express, https://developers.redhat.com/blog/2018/04/16/zero-express-openshift-3-commands/,  before that `--deploy.port` flag was in nodeshift,  I probably should add a note in it.

I know i said earlier, i'm not sure if making 3000 the default port feels right, but If we find other frameworks in the node community are defaulting to 3000, then perhaps we make the change.

This would be a major version change though, and would require us to update the boosters(probably with just the --deploy.port flag to 8080)
